const speciesList = [
  {
    category: "Mollusks",
    species: [
      { id: "black-katy-chiton", name: "Black Katy Chiton", scientific: "Katharina tunicata", description: "A large, dark-colored chiton commonly found on rocky shores." },
      { id: "gumboot-chiton", name: "Gumboot Chiton", scientific: "Cryptochiton stelleri", description: "The largest chiton species, also known as the 'wandering meatloaf'." },
      { id: "lined-chiton", name: "Lined Chiton", scientific: "Tonicella lineata", description: "A small, colorful chiton with intricate patterns on its plates." },
      { id: "leather-chiton", name: "Leather Chiton", scientific: "Placiphorella velata", description: "A soft-bodied chiton with a leathery girdle." },
      { id: "pacific-blue-mussel", name: "Pacific Blue Mussel", scientific: "Mytilus trossulus", description: "A common bivalve that forms dense clusters on rocks." },
      { id: "pacific-razor-clam", name: "Pacific Razor Clam", scientific: "Siliqua patula", description: "A fast-burrowing clam found on sandy beaches." },
      { id: "butter-clam", name: "Butter Clam", scientific: "Saxidomus gigantea", description: "A large, edible clam found in the intertidal zone." },
      { id: "manila-clam", name: "Manila Clam", scientific: "Venerupis philippinarum", description: "A small, filter-feeding clam common in muddy and sandy areas." },
      { id: "native-littleneck-clam", name: "Native Littleneck Clam", scientific: "Leukoma staminea", description: "A small, round-shelled clam found in sandy tide pools." },
      { id: "heart-cockle", name: "Heart Cockle", scientific: "Clinocardium nuttallii", description: "A large, heart-shaped bivalve that burrows in soft sediment." },
      { id: "littorine-periwinkles", name: "Littorine Periwinkles", scientific: "Littorina", description: "Small marine snails that cling to rocks in the intertidal zone." },
      { id: "oregon-triton", name: "Oregon Triton", scientific: "Fusitriton oregonensis", description: "A large predatory snail that feeds on other mollusks." },
      { id: "checkered-periwinkle", name: "Checkered Periwinkle", scientific: "Littorina scutulata", description: "A small, checkered-patterned snail found in the upper intertidal zone." },
      { id: "leafy-hornmouth-snail", name: "Leafy Hornmouth Snail", scientific: "Ceratostoma foliatum", description: "A spiny marine snail with distinctive leafy projections on its shell." },
      { id: "wrinkled-whelk", name: "Wrinkled Whelk", scientific: "Nucella lamellosa", description: "A carnivorous snail that preys on barnacles and mussels." },
      { id: "ribbed-limpet", name: "Ribbed Limpet", scientific: "Lottia digitalis", description: "A cone-shaped limpet that clings tightly to rocks." },
      { id: "shield-limpet", name: "Shield Limpet", scientific: "Lottia pelta", description: "A smooth, oval limpet often found in the mid-intertidal zone." },
      { id: "keyhole-limpet", name: "Keyhole Limpet", scientific: "Diodora aspera", description: "A limpet with a small hole at the top of its shell for water circulation." },
      { id: "shaggy-mouse-nudibranch", name: "Shaggy Mouse Nudibranch", scientific: "Aeolidia papillosa", description: "A white, fuzzy-looking sea slug that preys on anemones." },
      { id: "frosted-nudibranch", name: "Frosted Nudibranch", scientific: "Dirona albolineata", description: "A translucent, white nudibranch with delicate cerata." },
      { id: "opalescent-nudibranch", name: "Opalescent Nudibranch", scientific: "Hermissenda crassicornis", description: "A striking nudibranch with orange, blue, and white markings." },
    ],
  },
  
  
  {
    category: "Cephalopods",
    species: [
      { id: "giant-pacific-octopus", name: "Giant Pacific Octopus", scientific: "Enteroctopus dofleini", description: "The largest species of octopus, known for its intelligence and camouflage abilities." },
      { id: "red-octopus", name: "Red Octopus", scientific: "Octopus rubescens", description: "A small, reddish-brown octopus that inhabits tide pools and rocky shores." },
    ],
  },
  {
    category: "Crustaceans",
    species: [
      { id: "acorn-barnacles", name: "Acorn Barnacles", scientific: "Balanus glandula", description: "Small, volcano-shaped barnacles that attach to rocks and other hard surfaces." },
      { id: "thatched-barnacle", name: "Thatched Barnacle", scientific: "Semibalanus cariosus", description: "A large barnacle with a rough, conical shell." },
      { id: "dungeness-crab", name: "Dungeness Crab", scientific: "Metacarcinus magister", description: "A prized seafood species known for its sweet, tender meat." },
      { id: "helmet-crab", name: "Helmet Crab", scientific: "Telmessus cheiragonus", description: "A small, spiny crab often found in eelgrass beds." },
      { id: "kelp-crab", name: "Kelp Crab", scientific: "Pugettia producta", description: "A crab with long legs that blends in with seaweed and kelp." },
      { id: "porcelain-crab", name: "Porcelain Crab", scientific: "Petrolisthes", description: "A delicate crab that filters plankton from the water." },
      { id: "shore-crab", name: "Shore Crab", scientific: "Hemigrapsus nudus", description: "A small crab with purple or green coloration that scurries along tide pools." },
      { id: "red-rock-crab", name: "Red Rock Crab", scientific: "Cancer productus", description: "A robust, red-colored crab often found on rocky shorelines." },
      { id: "sand-fleas-beach-hoppers", name: "Sand Fleas/Beach Hoppers", scientific: "Megalorchestia", description: "Small crustaceans that jump and burrow in sandy beaches." },
    ],
  },
  
  {
    category: "Echinoderms",
    species: [
      { id: "ochre-sea-star", name: "Ochre Sea Star", scientific: "Pisaster ochraceus", description: "A keystone predator known for its striking orange, purple, or brown color." },
      { id: "mottled-star", name: "Mottled Star", scientific: "Evasterias troschelii", description: "A large sea star with a mottled color pattern." },
      { id: "leather-star", name: "Leather Star", scientific: "Dermasterias imbricata", description: "A soft-bodied sea star with a leathery texture." },
      { id: "sunflower-sea-star", name: "Sunflower Sea Star", scientific: "Pycnopodia helianthoides", description: "A fast-moving sea star with up to 24 arms." },
      { id: "blood-star", name: "Blood Star", scientific: "Henricia spp.", description: "A small, bright red or orange sea star often found on rocks or kelp." },
      { id: "six-armed-sea-star", name: "Six-armed Sea Star", scientific: "Leptasterias spp.", description: "A small, cryptic sea star that hides among rocks and seaweed." },
      { id: "bat-star", name: "Bat Star", scientific: "Patiria miniata", description: "A short-armed sea star with a broad, bat-like shape." },
      { id: "velvet-star", name: "Velvet Star", scientific: "Hippasteria spinosa", description: "A deep red or pink sea star with a velvety texture." },
      { id: "green-sea-urchin", name: "Green Sea Urchin", scientific: "Strongylocentrotus droebachiensis", description: "A spiky, green-colored sea urchin that grazes on algae." },
      { id: "red-sea-urchin", name: "Red Sea Urchin", scientific: "Mesocentrotus franciscanus", description: "A large, long-spined urchin harvested for its roe." },
      { id: "purple-sea-urchin", name: "Purple Sea Urchin", scientific: "Strongylocentrotus purpuratus", description: "A purple-colored sea urchin found in rocky subtidal areas." },
      { id: "california-sea-cucumber", name: "California Sea Cucumber", scientific: "Apostichopus californicus", description: "A soft-bodied echinoderm that filters detritus from the ocean floor." },
      { id: "orange-sea-cucumber", name: "Orange Sea Cucumber", scientific: "Cucumaria miniata", description: "A bright orange, filter-feeding sea cucumber that attaches to rocks." },
    ],
  },
  {
    category: "Cnidarians",
    species: [
      { id: "giant-green-anemone", name: "Giant Green Anemone", scientific: "Anthopleura xanthogrammica", description: "A large, bright green anemone that thrives in rocky tide pools." },
      { id: "aggregating-anemone", name: "Aggregating Anemone", scientific: "Anthopleura elegantissima", description: "A small anemone that forms dense clusters along the shore." },
      { id: "white-plumed-anemone", name: "White-Plumed Anemone", scientific: "Metridium farcimen", description: "A tall, elegant anemone with long, feathery tentacles." },
      { id: "painted-anemone", name: "Painted Anemone", scientific: "Urticina grebelnyi", description: "A vibrant red, orange, and green anemone with white markings." },
      { id: "christmas-anemone", name: "Christmas Anemone", scientific: "Urticina crassicornis", description: "A bright red and green anemone often found in deep tide pools." },
      { id: "fish-eating-anemone", name: "Fish-Eating Anemone", scientific: "Urticina piscivora", description: "A large anemone known to consume small fish." },
      { id: "moonglow-anemone", name: "Moonglow Anemone", scientific: "Anthopleura artemisia", description: "A small, solitary anemone often buried in sand or mud." },
      { id: "cloak-anemone", name: "Cloak Anemone", scientific: "Adamsia carciniopados", description: "A unique anemone that lives symbiotically with hermit crabs." },
      { id: "strawberry-anemone", name: "Strawberry Anemone", scientific: "Corynactis californica", description: "A small, vibrant red or pink anemone resembling a strawberry." },
    ],
  },
  
  
  {
    "category": "Fish",
    "species": [
      { "id": "tidepool-sculpin", "name": "Tidepool Sculpin", "scientific": "Oligocottus maculosus", "description": "A small, well-camouflaged fish that darts between rocks in tide pools." },
      { "id": "fluffy-sculpin", "name": "Fluffy Sculpin", "scientific": "Oligocottus snyderi", "description": "A tiny, fuzzy-looking fish that blends into its environment." },
      { "id": "coastrange-sculpin", "name": "Coastrange Sculpin", "scientific": "Cottus aleuticus", "description": "A small, cryptic fish that hides among rocks and seaweed." },
      { "id": "scalyhead-sculpin", "name": "Scalyhead Sculpin", "scientific": "Artedius harringtoni", "description": "A colorful, adaptable fish that changes patterns to match its surroundings." },
      { "id": "red-irish-lord", "name": "Red Irish Lord", "scientific": "Hemilepidotus hemilepidotus", "description": "A striking, red-patterned sculpin often found in deeper tide pools." },
      { "id": "great-sculpin", "name": "Great Sculpin", "scientific": "Myoxocephalus polyacanthocephalus", "description": "A larger, robust sculpin sometimes seen in subtidal pools." },
      { "id": "high-cockscomb", "name": "High Cockscomb", "scientific": "Anoplarchus purpurescens", "description": "A long, eel-like fish with a prominent dorsal ridge." },
      { "id": "rockweed-gunnel", "name": "Rockweed Gunnel", "scientific": "Apodichthys fucorum", "description": "A slippery, greenish-brown fish that blends into seaweed." },
      { "id": "crescent-gunnel", "name": "Crescent Gunnel", "scientific": "Pholis laeta", "description": "A banded fish often found hiding under algae-covered rocks." },
      { "id": "saddleback-gunnel", "name": "Saddleback Gunnel", "scientific": "Pholis ornata", "description": "A small, brown and white gunnel with distinctive saddle-like markings." },
      { "id": "penpoint-gunnel", "name": "Penpoint Gunnel", "scientific": "Apodichthys flavidus", "description": "A long, thin fish with a pointed snout, often found under rocks." },
      { "id": "mosshead-warbonnet", "name": "Mosshead Warbonnet", "scientific": "Chirolophis nugator", "description": "A bizarre-looking fish with frilly appendages on its head." },
      { "id": "pacific-staghorn-sculpin", "name": "Pacific Staghorn Sculpin", "scientific": "Leptocottus armatus", "description": "A spiny-headed sculpin with large pectoral fins, common in tide pools." },
      { "id": "snake-prickleback", "name": "Snake Prickleback", "scientific": "Lumpenus sagitta", "description": "A long, snake-like fish that hides in crevices." },
      { "id": "longfin-sculpin", "name": "Longfin Sculpin", "scientific": "Jordania zonope", "description": "A well-camouflaged fish with long pectoral fins, often found in rocky pools." },
      { "id": "leopard-droidfish", "name": "Leopard Droidfish", "scientific": "Cyberichthys maculatus", "description": "A rare, highly adaptive fish with a sleek, mechanical-like pattern resembling leopard spots." }
    ]
  },
  
  {
    category: "Algae / Plants",
    species: [
      { id: "rockweed", name: "Rockweed", scientific: "Fucus distichus", description: "A brown seaweed that grows in dense mats along the shore." },
      { id: "bladderwrack", name: "Bladderwrack", scientific: "Fucus vesiculosus", description: "A brown algae with air bladders that help it float." },
      { id: "bull-kelp", name: "Bull Kelp", scientific: "Nereocystis luetkeana", description: "A fast-growing kelp that forms underwater forests." },
      { id: "giant-kelp", name: "Giant Kelp", scientific: "Macrocystis pyrifera", description: "One of the largest and fastest-growing kelp species." },
      { id: "sugar-kelp", name: "Sugar Kelp", scientific: "Saccharina latissima", description: "A large, edible kelp known for its sweet flavor." },
      { id: "split-kelp", name: "Split Kelp", scientific: "Laminaria setchellii", description: "A kelp species found in subtidal rocky areas." },
      { id: "winged-kelp", name: "Winged Kelp", scientific: "Alaria marginata", description: "A kelp with wavy, ruffled edges." },
      { id: "five-ribbed-kelp", name: "Five-Ribbed Kelp", scientific: "Costaria costata", description: "A kelp with distinctive rib-like structures." },
      { id: "tufted-algae", name: "Tufted Algae", scientific: "Sphacelaria spp.", description: "Small brown algae that form dense tufts on rocks." },
      { id: "sea-lettuce", name: "Sea Lettuce", scientific: "Ulva lactuca", description: "A bright green algae often found in tide pools." },
      { id: "gutweed", name: "Gutweed", scientific: "Ulva intestinalis", description: "A tubular, bright green algae found in brackish water." },
      { id: "spongeweed", name: "Spongeweed", scientific: "Codium fragile", description: "A spongy, branching green algae." },
      { id: "turkish-washcloth", name: "Turkish Washcloth", scientific: "Mastocarpus papillatus", description: "A red algae with a rough, sandpapery texture." },
      { id: "nori-pacific-laver", name: "Nori (Pacific Laver)", scientific: "Pyropia spp.", description: "A red algae commonly used in sushi." },
      { id: "dulse", name: "Dulse", scientific: "Palmaria mollis", description: "An edible red algae with a soft, leafy texture." },
      { id: "iridaea-rainbow-seaweed", name: "Iridaea (Rainbow Seaweed)", scientific: "Mazzaella spp.", description: "A mid to low intertidal red algae." },
      { id: "black-tar-spot-algae", name: "Black Tar Spot Algae", scientific: "Mastocarpus spp.", description: "Forms dark patches on rocks." },
      { id: "sea-sac", name: "Sea Sac", scientific: "Halosaccion glandiforme", description: "A water-filled, balloon-like red algae." },
      { id: "eelgrass", name: "Eelgrass", scientific: "Zostera marina", description: "A vital seagrass providing habitat for juvenile fish and invertebrates." },
      { id: "dwarf-eelgrass", name: "Dwarf Eelgrass", scientific: "Zostera japonica", description: "Found in intertidal sandy flats." },
      { id: "surfgrass", name: "Surfgrass", scientific: "Phyllospadix spp.", description: "A flowering seagrass growing in wave-swept rocky zones." },
    ],
  },
  
  {
    category: "Mammals",
    species: [
      { id: "sea-otter", name: "Sea Otter", scientific: "Enhydra lutris", description: "A playful marine mammal known for floating on its back and using tools to break open shellfish." },
      { id: "harbor-seal", name: "Harbor Seal", scientific: "Phoca vitulina", description: "A spotted seal that often hauls out on rocky shores and ice floes." },
      { id: "steller-sea-lion", name: "Steller Sea Lion", scientific: "Eumetopias jubatus", description: "A large, social sea lion that can often be seen lounging on rocks and docks." },
      { id: "humpback-whale", name: "Humpback Whale", scientific: "Megaptera novaeangliae", description: "A massive whale known for its acrobatic breaches and long, haunting songs." },
      { id: "orca-killer-whale", name: "Orca (Killer Whale)", scientific: "Orcinus orca", description: "A powerful predator that travels in pods and preys on fish, seals, and even other whales." },
      { id: "gray-whale", name: "Gray Whale", scientific: "Eschrichtius robustus", description: "A baleen whale known for its long migration along the Pacific coast." },
      { id: "minke-whale", name: "Minke Whale", scientific: "Balaenoptera acutorostrata", description: "A small baleen whale often seen feeding near the coast." },
      { id: "fin-whale", name: "Fin Whale", scientific: "Balaenoptera physalus", description: "The second-largest whale, occasionally seen in offshore waters." },
      { id: "dalls-porpoise", name: "Dall’s Porpoise", scientific: "Phocoenoides dalli", description: "A fast-swimming, black-and-white porpoise known for bow-riding boats." },
      { id: "harbor-porpoise", name: "Harbor Porpoise", scientific: "Phocoena phocoena", description: "A shy, small porpoise often seen near shorelines." },
    ],
  },

  {
    category: "Birds",
    species: [
      { id: "black-oystercatcher", name: "Black Oystercatcher", scientific: "Haematopus bachmani", description: "A striking black shorebird with a bright orange bill, often seen foraging on mussels and barnacles." },
      { id: "wandering-tattler", name: "Wandering Tattler", scientific: "Tringa incana", description: "A grayish shorebird that moves along rocky coasts searching for small invertebrates." },
      { id: "surfbird", name: "Surfbird", scientific: "Calidris virgata", description: "A stocky shorebird with a short, stout bill that forages along rocky shorelines." },
      { id: "ruddy-turnstone", name: "Ruddy Turnstone", scientific: "Arenaria interpres", description: "A boldly patterned shorebird that flips over rocks and seaweed looking for food." },
      { id: "black-turnstone", name: "Black Turnstone", scientific: "Arenaria melanocephala", description: "A dark shorebird commonly seen on rocky coasts, flipping over debris for food." },
      { id: "western-sandpiper", name: "Western Sandpiper", scientific: "Calidris mauri", description: "A small shorebird that migrates through the area and feeds on small marine invertebrates." },
      { id: "least-sandpiper", name: "Least Sandpiper", scientific: "Calidris minutilla", description: "The smallest shorebird in North America, often found foraging along the water's edge." },
      { id: "glaucous-winged-gull", name: "Glaucous-winged Gull", scientific: "Larus glaucescens", description: "A large, pale gull that scavenges along shorelines." },
      { id: "mew-gull", name: "Mew Gull", scientific: "Larus canus", description: "A smaller gull with a yellow bill, often seen searching for food in tide pools." },
      { id: "bonapartes-gull", name: "Bonaparte’s Gull", scientific: "Chroicocephalus philadelphia", description: "A small, delicate gull with a black head in summer." },
      { id: "pelagic-cormorant", name: "Pelagic Cormorant", scientific: "Urile pelagicus", description: "A dark seabird that dives underwater to catch fish, often seen perched on rocky outcrops." },
      { id: "double-crested-cormorant", name: "Double-crested Cormorant", scientific: "Nannopterum auritum", description: "A larger cormorant with an orange throat patch, sometimes spotted along the coast." },
      { id: "harlequin-duck", name: "Harlequin Duck", scientific: "Histrionicus histrionicus", description: "A striking, colorful duck that forages along rocky intertidal zones." },
      { id: "common-merganser", name: "Common Merganser", scientific: "Mergus merganser", description: "A fish-eating duck often seen swimming in coastal waters." },
      { id: "red-breasted-merganser", name: "Red-breasted Merganser", scientific: "Mergus serrator", description: "A sleek diving duck with a shaggy crest, found along shorelines." },
      { id: "great-blue-heron", name: "Great Blue Heron", scientific: "Ardea herodias", description: "A large, long-legged wader often seen hunting in tide pools for fish and crustaceans." },
    ],
  },
  
];

export default speciesList;
